### PR TITLE
Capitalization on README.md

### PR DESCRIPTION
**Pull request by jjasghar**
VMware capitalization.

### CODE REVIEW

**Review by chris-rock — CHANGES_REQUESTED** [review]
Thank you for improving the our readme @jjasghar Could you please sign-off your PR?

**Comment by jjasghar** [comment]
Updated. Can we re-run DCO? /cc @robbkidd

**Comment by chris-rock** [comment]
It seems like this is still not signed...

**Comment by jjasghar** [comment]
But-but-but it is?

image

**Comment by jjasghar** [comment]
Reopened here: https://github.com/chef/inspec-vmware/pull/17

**Pull request closed without merging**
